# Generated by Django 3.1.2 on 2020-10-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='wallet',
            field=models.FloatField(default=0.0),
        ),
    ]
