# Generated by Django 3.1.2 on 2020-10-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermodel_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferal',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
